"""Logical model definitions: platform → containers → datasets → physical-child links.

The rest of the pipeline treats datasets and containers as technical metadata
owned by ingestion and only syncs enrichment onto them. Logical models break
that assumption: they are hand-authored datasets on a platform whose
dataPlatformInfo.logical is true (DataHub v2.1+ / OSS v1.7+) and exist on no
source system. So every logical platform in scope is ALWAYS exported in full.
`logical == true` is the only signal; pre-v2.1 conventions are not detected.
"""

import logging

from datahub.emitter.mce_builder import make_schema_field_urn
from datahub.emitter.mcp import MetadataChangeProposalWrapper
from datahub.ingestion.graph.client import DataHubGraph
from datahub.ingestion.graph.openapi import RelationshipDirection
from datahub.metadata.schema_classes import (
    ContainerClass,
    ContainerPropertiesClass,
    DataPlatformInfoClass,
    DataPlatformInstanceClass,
    DatasetPropertiesClass,
    EditableDatasetPropertiesClass,
    LogicalParentClass,
    SchemaMetadataClass,
    SubTypesClass,
)

from src.interfaces import EntityHandler, UrnMapper
from src.logical_layout import parent_container, read_tree, write_tree
from src.retry import retry_transient
from src.utils import topological_sort

logger = logging.getLogger(__name__)

# Definition aspects only. Tags/terms/owners/domains stay in enrichment export;
# browsePathsV2, status and key aspects are regenerated by GMS.
DEFINITION_ASPECTS: dict[str, tuple[type, ...]] = {
    "dataPlatform": (DataPlatformInfoClass,),
    "container": (ContainerPropertiesClass, ContainerClass, SubTypesClass, DataPlatformInstanceClass),
    "dataset": (DatasetPropertiesClass, SchemaMetadataClass, ContainerClass, EditableDatasetPropertiesClass, SubTypesClass),
}
PHYSICAL_CHILD = "physicalChild"
_LOGICAL_FILTER = [{"field": "logical", "condition": "EQUAL", "values": ["true"]}]


def _platform_urn(platform: str) -> str:
    return platform if platform.startswith("urn:li:dataPlatform:") else f"urn:li:dataPlatform:{platform}"


def _cyclic_containers(entities: list[dict]) -> dict[str, list[str]]:
    """Containers whose parent chain within the files loops, mapped to that chain.

    Covers the loop members and any container hanging below a loop: neither can
    be ordered parents-first. They fail; datasets under them then require the
    parent on the target like any container missing from the files.
    """
    parents = {
        e["urn"]: parent_container(e) for e in entities if e["entityType"] == "container" and "_load_error" not in e
    }
    cyclic: dict[str, list[str]] = {}
    for urn in parents:
        chain = [urn]
        while (nxt := parents.get(chain[-1])) is not None and nxt in parents:
            if nxt in chain:
                cyclic[urn] = chain + [nxt]
                break
            chain.append(nxt)
    return cyclic


class LogicalModelHandler(EntityHandler):
    def __init__(self, platforms: list[str] | None = None) -> None:
        self.platforms = platforms

    @property
    def entity_type(self) -> str:
        return "logicalModel"

    # ── export ────────────────────────────────────────────────────────────

    def export(self, graph: DataHubGraph) -> list[dict]:
        platforms = self._logical_platforms(graph)
        entities = [self._fetch(graph, p) for p in platforms]
        datasets = []
        for p in platforms:
            for urn in graph.get_urns_by_filter(entity_types=["dataset"], platform=p):
                ds = self._fetch(graph, urn)
                children = self._physical_children(graph, urn)
                if children:
                    ds["physicalChildren"] = children
                datasets.append(ds)
        entities += self._containers(graph, datasets) + datasets
        logger.info(f"Exported {len(datasets)} logical models across {len(platforms)} logical platforms")
        return entities

    def write_export(self, entities: list[dict], output_dir: str) -> None:
        # Scoped export owns only the requested platforms' folders (logical or not:
        # a non-logical platform owns a folder that never exists, so nothing is removed).
        scope = [_platform_urn(p) for p in self.platforms] if self.platforms else None
        write_tree(entities, output_dir, platforms=scope)

    def _logical_platforms(self, graph: DataHubGraph) -> list[str]:
        if self.platforms:
            candidates = [_platform_urn(p) for p in self.platforms]
        else:
            candidates = list(graph.get_urns_by_filter(entity_types=["dataPlatform"], extraFilters=_LOGICAL_FILTER))
        logical = []
        for p in candidates:
            info = graph.get_aspect(p, DataPlatformInfoClass)
            if info and info.logical:
                logical.append(p)
            else:
                logger.info(f"{p} is not a logical platform; its datasets are left to enrichment export")
        return logical

    def _fetch(self, graph: DataHubGraph, urn: str) -> dict:
        entity_type = urn.split(":")[2]
        if entity_type == "dataPlatform":
            # dataPlatform has exactly one definition aspect, so fetch it directly
            # via get_aspect rather than get_entity_semityped's bulk-aspect path
            # (which is built for containers/datasets that carry several aspects).
            return self._fetch_platform(graph, urn)
        names = [cls.ASPECT_NAME for cls in DEFINITION_ASPECTS[entity_type]]

        @retry_transient(max_retries=3, base_delay=1.0)
        def _get():
            return graph.get_entity_semityped(urn, aspects=names)

        bag = _get()
        return {
            "urn": urn,
            "entityType": entity_type,
            "aspects": {name: bag[name].to_obj() for name in names if name in bag},
        }

    def _fetch_platform(self, graph: DataHubGraph, urn: str) -> dict:
        @retry_transient(max_retries=3, base_delay=1.0)
        def _get():
            return graph.get_aspect(urn, DataPlatformInfoClass)

        info = _get()
        return {
            "urn": urn,
            "entityType": "dataPlatform",
            "aspects": {DataPlatformInfoClass.ASPECT_NAME: info.to_obj()} if info else {},
        }

    def _containers(self, graph: DataHubGraph, datasets: list[dict]) -> list[dict]:
        """Every container referenced by an exported dataset, plus all ancestors."""
        found: dict[str, dict] = {}
        pending = [c for c in map(parent_container, datasets) if c]
        while pending:
            urn = pending.pop()
            if urn in found:
                continue
            container = self._fetch(graph, urn)
            if not container["aspects"]:
                logger.warning(f"{urn} is referenced by a logical model but does not exist; not exported")
                continue
            found[urn] = container
            parent = parent_container(container)
            if parent:
                pending.append(parent)
        return sorted(found.values(), key=lambda c: c["urn"])

    def _physical_children(self, graph: DataHubGraph, model_urn: str) -> list[dict]:
        """logicalParent edges stored on physical datasets and their schemaFields."""
        field_prefix = f"urn:li:schemaField:({model_urn},"
        children = []
        related = graph.get_related_entities(
            model_urn, relationship_types=["PhysicalInstanceOf"], direction=RelationshipDirection.INCOMING
        )
        for child_urn in sorted({r.urn for r in related if r.urn.startswith("urn:li:dataset:")}):
            child: dict = {"urn": child_urn}
            parent = graph.get_aspect(child_urn, LogicalParentClass)
            if parent:
                child["logicalParent"] = parent.to_obj()
            schema = graph.get_aspect(child_urn, SchemaMetadataClass)
            fields = []
            for f in schema.fields if schema else []:
                sf_urn = make_schema_field_urn(child_urn, f.fieldPath)
                link = graph.get_aspect(sf_urn, LogicalParentClass)
                if link and link.parent and link.parent.destinationUrn.startswith(field_prefix):
                    fields.append({"urn": sf_urn, "logicalParent": link.to_obj()})
            if fields:
                child["fields"] = fields
            children.append(child)
        return children

    # ── sync ──────────────────────────────────────────────────────────────

    def read_export(self, metadata_dir: str) -> list[dict]:
        """Load logicalModels/ in write order: platforms, containers (parents first), datasets, links."""
        entities = read_tree(metadata_dir)
        cyclic = _cyclic_containers(entities)
        entities = [
            {"urn": e["urn"], "entityType": "invalid", "_load_error": f"{e['urn']}: container cycle via {cyclic[e['urn']]}"}
            if e["urn"] in cyclic
            else e
            for e in entities
        ]
        invalid = [e for e in entities if "_load_error" in e]
        valid = [e for e in entities if "_load_error" not in e]
        known = {e["urn"] for e in valid}
        platforms = sorted((e for e in valid if e["entityType"] == "dataPlatform"), key=lambda e: e["urn"])
        containers = topological_sort(
            [{**e, "_parent": parent_container(e)} for e in sorted(valid, key=lambda e: e["urn"]) if e["entityType"] == "container"],
            "_parent",
        )
        datasets = sorted((e for e in valid if e["entityType"] == "dataset"), key=lambda e: e["urn"])
        other = [e for e in valid if e["entityType"] not in ("dataPlatform", "container", "dataset")]
        for e in containers + datasets:
            parent = parent_container(e)
            if parent and parent not in known:
                e["_requires"] = parent  # parent must already exist on the target
        children = [
            {**child, "entityType": PHYSICAL_CHILD, "_requires": child["urn"]}
            for ds in datasets
            for child in ds.get("physicalChildren", [])
        ]
        return invalid + other + platforms + containers + datasets + children

    def required_target_urn(self, entity: dict, urn_mapper: UrnMapper) -> str | None:
        required = entity.get("_requires")
        return urn_mapper.map(required) if required else None

    def build_mcps(self, entity: dict, urn_mapper: UrnMapper) -> list[MetadataChangeProposalWrapper]:
        if "_load_error" in entity:
            raise ValueError(entity["_load_error"])
        if entity["entityType"] == PHYSICAL_CHILD:
            links = [(entity["urn"], entity["logicalParent"])] if "logicalParent" in entity else []
            links += [(f["urn"], f["logicalParent"]) for f in entity.get("fields", [])]
            return [
                MetadataChangeProposalWrapper(entityUrn=urn_mapper.map(urn), aspect=LogicalParentClass.from_obj(obj))
                for urn, obj in links
            ]
        classes = DEFINITION_ASPECTS.get(entity["entityType"])
        if classes is None:
            raise ValueError(f"Unsupported entity type under logicalModels/: {entity['urn']}")
        by_name = {cls.ASPECT_NAME: cls for cls in classes}
        unknown = sorted(set(entity["aspects"]) - set(by_name))
        if unknown:
            raise ValueError(f"{entity['urn']}: aspects not allowed for {entity['entityType']}: {unknown}")
        # ponytail: URN references nested inside aspects (e.g. container) pass through unmapped, like the rest of the pipeline
        return [
            MetadataChangeProposalWrapper(entityUrn=urn_mapper.map(entity["urn"]), aspect=by_name[name].from_obj(obj))
            for name, obj in entity["aspects"].items()
        ]
